# Generated by Django 6.0.2 on 2026-03-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0002_alter_character_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(blank=True, help_text='Imagen de fondo del tablero', null=True, upload_to='boards/')),
                ('config', models.JSONField(blank=True, help_text='Configuración del tablero (zoom, grid, etc.)', null=True)),
                ('campaign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='board', to='cantrip.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Nombre visible del token (si no hay personaje)', max_length=100)),
                ('x', models.FloatField(help_text='Posición X en el tablero')),
                ('y', models.FloatField(help_text='Posición Y en el tablero')),
                ('color', models.CharField(default='#ff0000', help_text='Color del token si no hay imagen', max_length=20)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='cantrip.board')),
                ('character', models.ForeignKey(blank=True, help_text='Personaje asociado a este token (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to='cantrip.character')),
            ],
        ),
    ]
