# Generated by Django 6.0.2 on 2026-03-25 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0003_board_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='background_static',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='boards/'),
        ),
    ]
