# Generated by Django 6.0.2 on 2026-03-25 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0004_board_background_static_alter_board_background_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='board',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_board', to='cantrip.board'),
        ),
        migrations.AlterField(
            model_name='board',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='cantrip.campaign'),
        ),
    ]
