# Generated by Django 6.0.2 on 2026-04-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0005_campaign_board_alter_board_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image_static',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='characters/'),
        ),
    ]
