# Generated by Django 6.0.2 on 2026-04-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0006_character_image_static_character_image_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen del token (si no es un personaje)', null=True, upload_to='tokens/'),
        ),
    ]
