# Generated by Django 6.0.2 on 2026-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0007_token_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='size',
            field=models.IntegerField(default=60, help_text='Tamaño base del token en píxeles'),
        ),
    ]
