# Generated by Django 6.0.2 on 2026-04-13 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0008_token_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='tokens',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='token',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_set', to='cantrip.board'),
        ),
    ]
