# Generated by Django 6.0.2 on 2026-04-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0009_board_tokens_alter_token_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cantrip.board'),
        ),
    ]
