# Generated by Django 6.0.2 on 2026-04-13 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0010_alter_token_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='tokens',
        ),
        migrations.AlterField(
            model_name='token',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='cantrip.board'),
        ),
    ]
