# Generated by Django 6.0.2 on 2026-05-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cantrip', '0012_boardnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='static_path',
            field=models.CharField(blank=True, help_text='Ruta estática del token (assets/tokens/...), evita copia a media', max_length=255, null=True),
        ),
    ]
